[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "rl-loco-mj"
version = "0.1.0"
description = "MJLab reinforcement-learning environments."
requires-python = ">=3.10,<3.14"
dependencies = [
  "mjlab>=1.6,<2",
  "rsl-rl-lib-local==3.0.1",
]

[project.entry-points."mjlab.tasks"]
rl_loco_mj = "rl_loco_mj.tasks"

[project.scripts]
train_ampvae = "rl_loco_mj.scripts.ampvae.train:main"
play_ampvae = "rl_loco_mj.scripts.ampvae.play:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["rl_loco_mj*"]

[tool.setuptools.package-data]
rl_loco_mj = [
  "asset_zoo/robots/*/xmls/*.xml",
  "asset_zoo/robots/*/xmls/assets/*.obj",
]

[tool.ruff]
src = ["src"]
exclude = ["rsl_rl_local"]
indent-width = 2
